name: we_eat
description: A menu bar selector

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2
  firebase_auth: ^0.6.6
  google_sign_in: ^3.2.4
  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.1
  json_serializable: ^2.0.1


flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/icons/
   - assets/images/
  fonts:
   - family: Open Sans
     fonts:
      - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
      - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
        weight: 900
      - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
        weight: 900
        style: italic
      - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
        style: italic
      - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
        weight: 600
        style: italic
